package org.crowdguru.datastore.constants;

public interface UserConstants {
	String USER_1_FORENAME = "USER_1_FORENAME"; 
	String USER_1_SURNAME = "USER_1_SURNAME";
	String USER_1_ABOUTME = "USER_1_ABOUTME";
	String USER_1_HOMETOWN = "USER_1_HOMETOWN";
	String USER_1_PROVIDER_ID = "USER_1_PROVIDER_ID";
	String USER_1_PROVIDER_USERID = "USER_1_PROVIDER_USERID";
	
	String USER_2_FORENAME = "USER_2_FORENAME"; 
	String USER_2_SURNAME = "USER_2_SURNAME";
	String USER_2_ABOUTME = "USER_2_ABOUTME";
	String USER_2_HOMETOWN = "USER_2_HOMETOWN";
	String USER_2_PROVIDER_ID = "USER_2_PROVIDER_ID";
	String USER_2_PROVIDER_USERID = "USER_2_PROVIDER_USERID";
	
	String USER_3_FORENAME = "USER_3_FORENAME"; 
	String USER_3_SURNAME = "USER_3_SURNAME";
	String USER_3_ABOUTME = "USER_3_ABOUTME";
	String USER_3_HOMETOWN = "USER_3_HOMETOWN";
	String USER_3_PROVIDER_ID = "USER_3_PROVIDER_ID";
	String USER_3_PROVIDER_USERID = "USER_3_PROVIDER_USERID";
}
