package org.crowdguru.datastore.constants;

public interface UserConstants {
	String USER_1_FORENAME = "USER_1_FORENAME"; 
	String USER_1_SURNAME = "USER_1_SURNAME";
	String USER_1_SHORTPROFILE = "USER_1_SHORTPROFILE";
	String USER_1_LOCATION = "USER_1_LOCATION";
	String USER_1_PROVIDER_ID = "USER_1_PROVIDER_ID";
	String USER_1_PROVIDER_USERID = "USER_1_PROVIDER_USERID";
	
	String USER_2_FORENAME = "USER_2_FORENAME"; 
	String USER_2_SURNAME = "USER_2_SURNAME";
	String USER_2_SHORTPROFILE = "USER_2_SHORTPROFILE";
	String USER_2_LOCATION = "USER_2_LOCATION";
	String USER_2_PROVIDER_ID = "USER_2_PROVIDER_ID";
	String USER_2_PROVIDER_USERID = "USER_2_PROVIDER_USERID";
	
	String USER_3_FORENAME = "USER_3_FORENAME"; 
	String USER_3_SURNAME = "USER_3_SURNAME";
	String USER_3_SHORTPROFILE = "USER_3_SHORTPROFILE";
	String USER_3_LOCATION = "USER_3_LOCATION";
	String USER_3_PROVIDER_ID = "USER_3_PROVIDER_ID";
	String USER_3_PROVIDER_USERID = "USER_3_PROVIDER_USERID";
}
